type Status = '未着手' | '進行中' | '保留中' | '完了' | '中止'
export type Todo = { id: string; title: string; status: Status; priority: string | null; memo: string; projectId: string | null }
export type Project = { id: string; name: string; fullName: string }

const TODO_SOURCE_ID = '3aefab19-d295-80e1-aa2b-000ba083e5a2'
const PROJECT_SOURCE_ID = '3aefab19-d295-8011-baac-000b974233e4'
const NOTION_VERSION = '2026-03-11'
let mockTodos: Todo[] = [{ id:'mock-1', title:'今日やることを整理する', status:'未着手', priority:'A: 重要度高 緊急度高', memo:'ボードで優先順を確認する。', projectId:'mock-project-1' },{ id:'mock-2', title:'仕様を確認する', status:'進行中', priority:'B: 重要度高 緊急度低', memo:'', projectId:'mock-project-1' },{ id:'mock-3', title:'週次レビューを終える', status:'保留中', priority:'C: 重要度低 緊急度高', memo:'金曜日に再開。', projectId:null }]
let mockProjects: Project[] = [{ id:'mock-project-1', name:'Todo App', fullName:'タスク管理アプリ' }]
const token = () => process.env.NOTION_API_KEY

async function notionFetch(path:string, init:RequestInit={}) { const response = await fetch(`https://api.notion.com/v1${path}`, { ...init, headers:{ Authorization:`Bearer ${token()}`, 'Notion-Version':NOTION_VERSION, 'Content-Type':'application/json', ...init.headers } }); if (!response.ok) throw createError({ statusCode:response.status, statusMessage:'Notion API request failed' }); return response.json() }
const title = (properties:any, property:string) => properties[property]?.title?.[0]?.plain_text ?? ''
const richText = (properties:any, property:string) => properties[property]?.rich_text?.map((item:any) => item.plain_text).join('') ?? ''
const toTodo = (page:any):Todo => ({ id:page.id, title:title(page.properties,'TODO'), status:page.properties['ステータス']?.status?.name ?? '未着手', priority:page.properties['優先度']?.select?.name ?? null, memo:richText(page.properties,'メモ'), projectId:page.properties['関連プロジェクト']?.relation?.[0]?.id ?? null })
export async function listData() { if (!token()) return { todos:mockTodos, projects:mockProjects, mode:'mock' as const }; const [todoResponse,projectResponse] = await Promise.all([notionFetch(`/data_sources/${TODO_SOURCE_ID}/query`,{method:'POST',body:JSON.stringify({page_size:100})}),notionFetch(`/data_sources/${PROJECT_SOURCE_ID}/query`,{method:'POST',body:JSON.stringify({page_size:100})})]); return { todos:todoResponse.results.map(toTodo), projects:projectResponse.results.map((page:any) => ({ id:page.id,name:title(page.properties,'プロジェクト略称'),fullName:richText(page.properties,'プロジェクト正式名所') })), mode:'notion' as const } }
export async function createProject(input:Pick<Project,'name'|'fullName'>) { if (!token()) { const project={id:`mock-project-${Date.now()}`,name:input.name,fullName:input.fullName}; mockProjects=[project,...mockProjects]; return project }; const page=await notionFetch('/pages',{method:'POST',body:JSON.stringify({parent:{type:'data_source_id',data_source_id:PROJECT_SOURCE_ID},properties:{'プロジェクト略称':{title:[{type:'text',text:{content:input.name}}]},'プロジェクト正式名所':{rich_text:input.fullName?[{type:'text',text:{content:input.fullName}}]:[]}}})}); return {id:page.id,name:input.name,fullName:input.fullName} }
export async function createTodo(input:Pick<Todo,'title'|'priority'|'memo'|'projectId'>) { if (!token()) { const todo:Todo={id:`mock-${Date.now()}`,title:input.title,status:'未着手',priority:input.priority,memo:input.memo,projectId:input.projectId};mockTodos=[todo,...mockTodos];return todo }; return toTodo(await notionFetch('/pages',{method:'POST',body:JSON.stringify({parent:{type:'data_source_id',data_source_id:TODO_SOURCE_ID},properties:{TODO:{title:[{type:'text',text:{content:input.title}}]},ステータス:{status:{name:'未着手'}},優先度:{select:input.priority?{name:input.priority}:null},メモ:{rich_text:input.memo?[{type:'text',text:{content:input.memo}}]:[]},関連プロジェクト:{relation:input.projectId?[{id:input.projectId}]:[]}}})})) }
export async function updateTodo(id:string,input:Partial<Pick<Todo,'title'|'status'|'priority'|'memo'|'projectId'>>) { if (!token()) { const todo=mockTodos.find((item)=>item.id===id);if(!todo) throw createError({statusCode:404,statusMessage:'Todo not found'});Object.assign(todo,input);return todo }; const properties:Record<string,unknown>={};if(input.title!==undefined)properties.TODO={title:[{type:'text',text:{content:input.title}}]};if(input.status!==undefined)properties.ステータス={status:{name:input.status}};if(input.priority!==undefined)properties.優先度={select:input.priority?{name:input.priority}:null};if(input.memo!==undefined)properties.メモ={rich_text:input.memo?[{type:'text',text:{content:input.memo}}]:[]};if(input.projectId!==undefined)properties.関連プロジェクト={relation:input.projectId?[{id:input.projectId}]:[]};return toTodo(await notionFetch(`/pages/${id}`,{method:'PATCH',body:JSON.stringify({properties})})) }
export async function deleteTodo(id:string) { if (!token()) { const exists=mockTodos.some((item)=>item.id===id);if(!exists) throw createError({statusCode:404,statusMessage:'Todo not found'});mockTodos=mockTodos.filter((item)=>item.id!==id);return { id } }; await notionFetch(`/pages/${id}`,{method:'PATCH',body:JSON.stringify({in_trash:true})});return { id } }
